const a = 3;    // "CONST" UMA VARIAVEL CONSTANTE, QUE NÃO PODE SER ALTERADA NO CÓDIGO.

// O IDEAL NO CÓDIGO E CRIAR MAIS "CONST", DO QUE "VAR / LET" PARA OS DADOS QUE NÃO SERÃO ALTERADOS DENTRO DO CÓDIGO / PROGRAMA.

//...

// a = a + 10;

//...

console.log(a);