console.log("Passo #03");
console.log("Passo #02");
console.log("Passo #01");
/*A ORDEM IMPORTA NA HORA DE COLOCAR AS SENTENÇAS

AS SENTENÇAS DE CODIGO SÃO EXTREMAMENTE IMPORTANTES, A PRINCIPAL SENTENÇA QUE TODO PROGRAMADOR APRENDE É A DE 'PRINTAR ALGO NA TELA', OU MANDAR O COMPUTADOR 'PRINTAR NO TERMINAL' DETERMINADO CÓDIGO.

*/
