let a = 1;
let b = 2;

//console.log(++a === b++ ); //O VALOR "PRE"FIX DO 'A' É PROCESSADO PRIMEIRO POR SER UM OPERADOR PREFIX, DEPOIS VEM A OPERAÇÃO DE IGUALDADE RESTRITA. DEPOIS DE TER FEITO ISSO, QUANDO EXECUTADO CONSOLE.LOG NOVAMENTE PEDIDNDO PARA MOSTRAR OS VAORES DE (A === B) OS VALORES JÁ SERÃO ALTERADOS POR CONTA DA PRIORIDADE DA LINHA ANTERIOR.

//console.log(a ===b );

// MANEIRA MELHOR DE CODAR


a++
console.log(a === b);
b++

